#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidGesture.Resource", IsApplication=true)]

namespace AndroidGesture
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int down_arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_aboutus = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_client = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_contactus = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_event = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_help = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_home = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_product = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_service = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_solution = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int menu_icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int up_arrow = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int btnImgExpander = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int imgProfilePic = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int ivMenuImg = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int menuIconImgView = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int menuListView = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int titleBarLinearLayout = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int txtActionBarText = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int txtDescription = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int txtMnuText = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int txtPage = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MenuCustomLayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
